In [1]:
import numpy as np

In [2]:
import dask.dataframe as dd

In [3]:
from dask.distributed import Client

client = Client(n_workers=4)
client

In [4]:

ddf = dd.read_csv('C:/Users/user/Desktop/2019-Dec.csv')
ddf

Dask DataFrame Structure:
                event_time event_type product_id category_id category_code   brand    price user_id user_session
npartitions=146
                    object     object      int64       int64        object  object  float64   int64       object
                       ...        ...        ...         ...           ...     ...      ...     ...          ...
...                    ...        ...        ...         ...           ...     ...      ...     ...          ...
                       ...        ...        ...         ...           ...     ...      ...     ...          ...
                       ...        ...        ...         ...           ...     ...      ...     ...          ...
Dask Name: read-csv, 146 tasks

In [5]:

ddf.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-12-01 00:00:00 UTC,view,1005105,2232732093077520756,construction.tools.light,apple,1302.48,556695836,ca5eefc5-11f9-450c-91ed-380285a0bc80
1,2019-12-01 00:00:00 UTC,view,22700068,2232732091643068746,NaN,force,102.96,577702456,de33debe-c7bf-44e8-8a12-3bf8421f842a
2,2019-12-01 00:00:01 UTC,view,2402273,2232732100769874463,appliances.personal.massager,bosch,313.52,539453785,5ee185a7-0689-4a33-923d-ba0130929a76
3,2019-12-01 00:00:02 UTC,purchase,26400248,2053013553056579841,computers.peripherals.printer,NaN,132.31,535135317,61792a26-672f-4e61-9832-7b63bb1714db
4,2019-12-01 00:00:02 UTC,view,20100164,2232732110089618156,apparel.trousers,nika,101.68,517987650,906c6ca8-ff5c-419a-bde9-967ba8e2233e

In [6]:
import datetime
datetime.datetime.strptime('2019-12-01 00:00:02 UTC','%Y-%m-%d %H:%M:%S UTC').date()

datetime.date(2019, 12, 1)

In [7]:
def parsetime(x):
    try:
        return datetime.datetime.strptime(x,'%Y-%m-%d %H:%M:%S UTC').date()
    except:
        return datetime.datetime.strptime('2019-12-01 00:00:02 UTC','%Y-%m-%d %H:%M:%S UTC').date()

In [8]:
ddf = ddf[ddf.event_type == 'purchase']
ddf['event_time'].head()

3      2019-12-01 00:00:02 UTC
111    2019-12-01 00:00:39 UTC
267    2019-12-01 00:01:35 UTC
315    2019-12-01 00:01:54 UTC
332    2019-12-01 00:02:01 UTC
Name: event_time, dtype: object

In [9]:
ddf['event_time'] = ddf['event_time'].apply(parsetime)

C:\Users\user\anaconda3\lib\site-packages\dask\dataframe\core.py:3997: UserWarning:
You did not provide metadata, so Dask is running your function on a small dataset to guess output types. It is possible that Dask will guess incorrectly.
To provide an explicit output types or to silence this message, please provide the `meta=` keyword, as described in the map or apply function that you are using.
  Before: .apply(func)
  After:  .apply(func, meta=('event_time', 'object'))

  warnings.warn(meta_warning(meta))

In [10]:
ddf.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
3,2019-12-01,purchase,26400248,2053013553056579841,computers.peripherals.printer,NaN,132.31,535135317,61792a26-672f-4e61-9832-7b63bb1714db
111,2019-12-01,purchase,1004739,2232732093077520756,construction.tools.light,xiaomi,167.29,569958205,80afff78-be88-479a-8930-83b3e6220926
267,2019-12-01,purchase,1004833,2232732093077520756,construction.tools.light,samsung,167.03,557794415,6fecf566-ebb0-4e70-a243-cdc13ce044cb
315,2019-12-01,purchase,1004838,2232732093077520756,construction.tools.light,oppo,154.41,561593478,cc3328ce-e22a-49ba-b92a-3e143fb4b3d6
332,2019-12-01,purchase,1005003,2232732093077520756,construction.tools.light,huawei,227.64,555295228,3de3ac21-f446-4cf5-b3c3-06a051c5caa9

In [11]:
a = ddf.groupby("event_time").price.sum().compute()

In [16]:
a.head()

event_time
2019-12-01    8153753.43
2019-12-02    8320964.96
2019-12-03    7367826.76
2019-12-04    7370625.26
2019-12-05    7519208.14
Name: price, dtype: float64

In [13]:
ddf2 = ddf.repartition(1)
ddf2.to_csv('C:/Users/user/Desktop/dask_data')

['C:\\Users\\user\\Desktop\\dask_data\\0.part']

In [14]:
c = a.to_frame()

In [17]:
c.to_csv('C:/Users/user/Desktop/dsk3.csv')

In [ ]:
ddf['event_time'].unique().compute()

In [ ]:
ddf.columns